"""Add notes to order

Revision ID: 71489946dd34
Revises: 20260831_add_delivery_address
Create Date: 2026-09-03 18:04:00.428308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71489946dd34'
down_revision: Union[str, None] = '20260831_add_delivery_address'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fulfillment_type', sa.Enum('DELIVERY', 'PICKUP', name='fulfillmenttype_enum'), nullable=False, server_default='DELIVERY'))
    op.add_column('orders', sa.Column('notes', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_orders_fulfillment_type'), 'orders', ['fulfillment_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_fulfillment_type'), table_name='orders')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'fulfillment_type')
    # ### end Alembic commands ###
